// src/components/PublishForm/PublishForm.tsx
import React, { useState, useEffect, useMemo } from 'react'
import type { UndefinedOr } from '@devprotocol/util-ts'
import { i18nFactory, type ClubsI18nFunction } from '@devprotocol/clubs-core'

import { Strings } from './i18n'
import { Market } from '../PublishMarketForm/types'
import GithubMarketButton from '@components/PublishMarketForm/Github/Github'
import DiscordMarketButton from '@components/PublishMarketForm/Discord/Discord'
import YoutubeMarketButton from '@components/PublishMarketForm/Youtube/Youtube'

interface IPublishFormProps {
  domain: string
}

const PublishForm = (props: IPublishFormProps) => {
  let i18nBase = i18nFactory(Strings)
  let i18n: ClubsI18nFunction<typeof Strings> = i18nBase(['en'])

  const [clubsName, setClubsName] = useState<String>('')
  const [tokenName, setTokenName] = useState<String>('')
  const [tokenSymbol, setTokenSymbol] = useState<String>('')
  const [market, setMarket] = useState<UndefinedOr<Market>>(undefined)

  useEffect(() => {
    i18n = i18nBase(navigator.languages)
  }, [navigator])

  const toPublishConfirm = async () => {
    if (!props.domain || !clubsName || !market || !tokenName || !tokenSymbol) {
      return
    }

    // TODO: add validations for input field.
    window.location.href = new URL(
      `${props.domain}/setup/confirm?clubsName=${clubsName}&tokenName=${tokenName}&tokenSymbol=${tokenSymbol}`,
      `${location.protocol}//${location.host}`,
    ).toString()
  }

  return (
    <>
      <div className="relative flex gap-16 flex-col justify-center p-4 md:p-0 w-[36%] max-w-[36%] ml-auto mr-auto">
        <section className="mt-16 grid gap-8 md:mt-32 min-w-full w-full max-w-full">
          <h1 className="text-2xl font-bold md:text-5xl text-center">
            {i18n('Header')}
          </h1>
          <p>{i18n('SubHeader')}</p>
        </section>

        <section className="grid gap-16 w-full max-w-full mb-16 md:mb-32">
          <label className="hs-form-field is-filled is-required">
            <span className="hs-form-field__label">
              {i18n('ClubNameLabel')}
            </span>
            <input
              className="hs-form-field__input w-full"
              type="text"
              value={clubsName as string}
              onChange={(ev) => setClubsName(ev?.target?.value || '')}
              id="clubs-name"
              name="clubs-name"
            />
            <p className="hs-form-field__helper mt-2">
              * {i18n('ClubNameHelper', [props.domain])}
            </p>
          </label>

          <div className="hs-form-field is-filled is-required">
            <span className="hs-form-field__label">
              {' '}
              {i18n('VerifyYouLabel')}{' '}
            </span>
            <div className="flex w-full max-w-full h-28 max-h-[28] items-center justify-start gap-2">
              <GithubMarketButton market={market} changeMarket={setMarket} />
              <DiscordMarketButton market={market} changeMarket={setMarket} />
              <YoutubeMarketButton market={market} changeMarket={setMarket} />
            </div>
            <p
              className={`${!market && 'hs-form-field__helper'} mt-2 font-body font-bold text-base capitalize`}
              dangerouslySetInnerHTML={{
                __html: `${i18n('VerifiedYouHelper', [market])}`,
              }}
            ></p>
          </div>

          <label className="hs-form-field is-filled is-required">
            <span className="hs-form-field__label">
              {i18n('TokenNameLabel')}
            </span>
            <input
              className="hs-form-field__input w-full"
              type="text"
              value={tokenName as string}
              onChange={(ev) => setTokenName(ev?.target?.value || '')}
              id="token-name"
              name="token-name"
            />
            <p className="hs-form-field__helper mt-2">
              * {i18n('TokenNameHelper')}
            </p>
          </label>

          <label className="hs-form-field is-filled is-required">
            <span className="hs-form-field__label">
              {i18n('TokenSymbolLabel')}
            </span>
            <input
              className="hs-form-field__input w-full"
              type="text"
              value={tokenSymbol as string}
              onChange={(ev) => setTokenSymbol(ev?.target?.value || '')}
              id="token-symbol"
              name="token-symbol"
            />
            <p className="hs-form-field__helper mt-2">
              * {i18n('TokenSymbolHelper')}
            </p>
          </label>

          <div className="flex w-full justify-end gap-[20px]">
            <button
              disabled={
                !props.domain ||
                !clubsName ||
                !market ||
                !tokenName ||
                !tokenSymbol
              }
              className={`hs-button is-filled is-error w-fit py-6 px-8 ${
                false ? 'animate-pulse bg-gray-500/60' : ''
              }`}
              onClick={toPublishConfirm}
            >
              <span className="hs-button__label">{i18n('Next')}</span>
            </button>
          </div>
        </section>
      </div>
    </>
  )
}

export default PublishForm

// src/components/PublishForm/PublishForm.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { i18nFactory, type ClubsConfiguration } from '@devprotocol/clubs-core'

  import { Strings } from './i18n'
  import { Market } from '../PublishMarketForm/types'
  import GithubIcon from '../PublishMarketForm/Github/GithubIcon.svelte'
  import YoutubeIcon from '../PublishMarketForm/Youtube/YoutubeIcon.svelte'
  import DiscordIcon from '../PublishMarketForm/Discord/DiscordIcon.svelte'

  const i18nBase = i18nFactory(Strings)
  let i18n = i18nBase(['en'])

  export let domain: string = ''

  let clubsName: string = ''
  let tokenName: string = ''
  let tokenSymbol: string = ''
  let creatorPlatform: Market

  const changeCreatorPlatform = async (platform: Market) => {
    creatorPlatform = platform
  }

  const toConfirm = async () => {
    // TODO: add validations for input field.
    window.location.href = new URL(
      `${domain}/setup/confirm?clubsName=${clubsName}&tokenName=${tokenName}&tokenSymbol=${tokenSymbol}`,
      `${location.protocol}//${location.host}`,
    ).toString()
  }

  onMount(() => {
    i18n = i18nBase(navigator.languages)
  })
</script>

<div
  class="relative flex gap-16 flex-col justify-center p-4 md:p-0 w-[36%] max-w-[36%] ml-auto mr-auto"
>
  <!-- Hero Header -->
  <section class="mt-16 grid gap-8 md:mt-32 min-w-full w-full max-w-full">
    <h1 class="text-2xl font-bold md:text-5xl text-center">{i18n('Header')}</h1>
    <!-- When want to add this to future we need to add translation and uncomment code of this line. -->
    <!-- <p>{i18n('SubHeader')}</p> -->
  </section>

  <!-- Core inputs -->
  <section class="grid gap-16 w-full max-w-full mb-16 md:mb-32">
    <!-- Clubs name -->
    <label class="hs-form-field is-filled is-required">
      <span class="hs-form-field__label">{i18n('ClubNameLabel')}</span>
      <input
        class="hs-form-field__input w-full"
        bind:value={clubsName}
        id="clubs-name"
        name="clubs-name"
      />
      <p class="hs-form-field__helper mt-2">
        * {i18n('ClubNameHelper', [domain])}
      </p>
    </label>

    <!-- Verify it's you -->
    <div class="hs-form-field is-filled is-required">
      <span class="hs-form-field__label"> {i18n('VerifyYouLabel')} </span>
      <div
        class="flex w-full max-w-full h-28 max-h-[28] items-center justify-start gap-2"
      >
        <button
          on:click|preventDefault={() => changeCreatorPlatform(Market.YOUTUBE)}
          class={`hs-button is-large is-filled flex flex-col max-w-[33%] grow items-center justify-center gap-2.5 ${
            creatorPlatform !== Market.YOUTUBE && 'opacity-50'
          } self-stretch justify-self-stretch h-full max-h-full min-h-full`}
          id="youtube-icon"
          name="youtube-icon"
          disabled={creatorPlatform === Market.YOUTUBE}
        >
          <span class="h-auto w-auto">
            <YoutubeIcon />
          </span>
          Youtube
        </button>
        <button
          on:click|preventDefault={() => changeCreatorPlatform(Market.GITHUB)}
          class={`hs-button is-large is-filled flex flex-col max-w-[33%] grow items-center justify-center gap-2.5 ${
            creatorPlatform !== Market.GITHUB && 'opacity-50'
          } self-stretch justify-self-stretch h-full max-h-full min-h-full`}
          id="github-icon"
          name="github-icon"
          disabled={creatorPlatform === Market.GITHUB}
        >
          <span class="h-auto w-auto">
            <GithubIcon />
          </span>
          Github
        </button>
        <button
          on:click|preventDefault={() => changeCreatorPlatform(Market.DISCORD)}
          class={`hs-button is-large is-filled flex flex-col max-w-[33%] grow items-center justify-center gap-2.5 ${
            creatorPlatform !== Market.DISCORD && 'opacity-50'
          } self-stretch justify-self-stretch h-full max-h-full min-h-full`}
          id="discord-icon"
          name="discord-icon"
          disabled={creatorPlatform === Market.DISCORD}
        >
          <span class="h-auto w-auto">
            <DiscordIcon />
          </span>
          Discord
        </button>
      </div>
      <p
        class={`${!creatorPlatform && 'hs-form-field__helper'} mt-2 font-body font-bold text-base capitalize`}
      >
        {@html i18n('VerifiedYouHelper', [creatorPlatform])}
      </p>
    </div>

    <!-- Token name -->
    <label class="hs-form-field is-filled is-required">
      <span class="hs-form-field__label">{i18n('TokenNameLabel')}</span>
      <input
        class="hs-form-field__input w-full"
        bind:value={tokenName}
        id="token-name"
        name="token-name"
      />
      <p class="hs-form-field__helper mt-2">
        * {i18n('TokenNameHelper')}
      </p>
    </label>

    <!-- Token symbol -->
    <label class="hs-form-field is-filled is-required">
      <span class="hs-form-field__label">{i18n('TokenSymbolLabel')}</span>
      <input
        class="hs-form-field__input w-full"
        bind:value={tokenSymbol}
        id="token-symbol"
        name="token-symbol"
      />
      <p class="hs-form-field__helper mt-2">
        * {i18n('TokenSymbolHelper')}
      </p>
    </label>

    <div class="flex w-full justify-end gap-[20px]">
      <button
        class={`hs-button is-filled is-error w-fit py-6 px-8 ${
          false ? 'animate-pulse bg-gray-500/60' : ''
        }`}
        on:click|preventDefault={toConfirm}
      >
        <span class="hs-button__label">{i18n('Next')}</span>
      </button>
    </div>
  </section>
</div>
