// src/components/Join/JoinClub.svelte
<script lang="ts">
  import ETH from '@assets/ETH.svg'
  import DEV from '@assets/devtoken.png'
  import type { Tiers } from '@constants/tier'
  import { providers } from 'ethers'
  import { composeTiers } from '@fixtures/utility'
  import type { UndefinedOr } from '@devprotocol/util-ts'
  import type { CurrencyOption } from '@constants/currencyOption'
  import MembershipOption from '@components/AdminMembershipsForm/MembershipOption.svelte'
  import { onMount } from 'svelte'

  export let propertyAddress: string
  export let tiers: Tiers
  export let tenantName: string
  export let rpcUrl: string
  export let preferedCurrency: 'dev' | 'eth'

  let currency: typeof preferedCurrency = preferedCurrency
  let composedTiers: { dev: Tiers; eth: Tiers } = {
    dev: preferedCurrency === 'dev' ? [...tiers] : [],
    eth: preferedCurrency === 'eth' ? [...tiers] : [],
  }

  onMount(async () => {
    if (preferedCurrency === 'eth') {
      return
    }
    composedTiers = await composeTiers({
      sourceTiers: tiers,
      provider: new providers.JsonRpcProvider(rpcUrl),
      tokenAddress: propertyAddress ?? '',
    })
  })

  const switchInputs = async (ev: Event) => {
    const { value } = ev.target as HTMLInputElement
    currency = value as 'dev' | 'eth'
  }
</script>

<section class="bg-dp-blue-grey-300 flex flex-col rounded-xl p-4 shadow">
  <h2 class="mb-4 text-4xl font-bold">Join</h2>
  <!-- DAOName from YAML config -->
  <div class="mb-8">Join {tenantName} in support of the project.</div>

  <h3 class="mb-4 text-2xl font-bold">Purchase with</h3>
  <form
    class={`mb-8 grid gap-2 ${
      preferedCurrency === 'dev' ? 'md:grid-cols-2' : ''
    }`}
  >
    {#if preferedCurrency === 'dev'}
      <label
        class={`flex items-center gap-2 rounded border p-8 py-4 ${
          currency === 'dev' ? 'border-native-blue-400' : 'border-white/20'
        }`}
      >
        <input
          class=""
          type="radio"
          name="input"
          value="dev"
          on:change={switchInputs}
          checked={preferedCurrency === 'dev'}
        />
        <img src={DEV} alt="DEV" class="h-8 w-8" />
        <span class="font-bold">DEV</span>
      </label>
    {/if}
    <label
      class={`flex items-center gap-2 rounded border p-8 py-4 ${
        currency === 'eth' ? 'border-native-blue-400' : 'border-white/20'
      }`}
    >
      <input
        class=""
        type="radio"
        name="input"
        value="eth"
        on:change={switchInputs}
        checked={preferedCurrency === 'eth'}
      />
      <img src={ETH} alt="ETH" class="h-8 w-8" />
      <span class="font-bold">ETH</span>
    </label>
  </form>

  <h3 class="mb-4 text-2xl font-bold">Select a membership</h3>
  <div class="mb-8 grid gap-8 lg:grid-cols-2">
    {#each composedTiers[currency] as tier, i}
      {#if tier.badgeImageSrc}
        <div>
          <MembershipOption
            name={tier.title}
            clubName={tenantName}
            imagePath={tier.badgeImageSrc}
            id={`${tier.id}:${currency}`}
            description={tier.badgeImageDescription}
            ethPrice={currency === 'eth' ? String(tier.amount) : undefined}
            devPrice={currency === 'dev' ? String(tier.amount) : undefined}
          />
          <a
            class="mt-2 block w-full rounded bg-black py-4 text-center text-sm font-semibold text-white"
            id={`select-opt-${i}-${currency}`}
            href={`/join/${tier.id}${
              currency !== 'dev' ? `?input=${currency}` : ''
            }`}>Select</a
          >
        </div>
      {/if}
    {/each}
  </div>
</section>

// src/components/Join/JoinClub.vue
<template>
  <section class="flex flex-col">
    <h2 class="mb-4 font-title text-4xl font-bold">Join</h2>
    <!-- DAOName from YAML config -->
    <div class="mb-8">Join {DAOName} in support of the project.</div>

    <h3 class="mb-4 font-title text-2xl font-bold">Purchase with</h3>
    <form class="mb-8 flex flex-col" ref="form">
      <label class="flex items-center py-4">
        <input
          class="w-16"
          type="radio"
          id="dev"
          name="input"
          value="dev"
          checked
          @change="switchInputs"
        />
        <span class="w-16">$DEV</span>
        <div class="flex items-center">
          <img
            src="/assets/devtoken.png"
            width="50"
            height="50"
            alt="dev token"
          />
          <span class="content-center justify-between text-sm"
            >Best way to sustainably support with staking.</span
          >
        </div>
      </label>
      <label class="flex items-center">
        <input
          class="w-16"
          type="radio"
          id="eth"
          name="input"
          value="eth"
          @change="switchInputs"
        />
        <span class="w-16">$ETH</span>
        <div class="flex items-center">
          <img src="/assets/ETH.svg" width="50" height="50" alt="ethereum" />
          <span class="content-center justify-between text-sm"
            >You will earn $DEV by staking.
          </span>
        </div>
      </label>
    </form>

    <h3 class="mb-4 font-title text-2xl font-bold">Select a tier</h3>
    <div class="mb-8 grid grid-cols-2 gap-8 lg:grid-cols-4">
      <Tier
        v-for="tier in tiers[currency]"
        v-bind:key="tier.id + tier.amount"
        :title="tier.title"
        :id="tier.id"
        :amount="tier.amount"
        :currency="currency"
        :badgeImageSrc="tier.badgeImageSrc"
      />
    </div>

    <section>
      <a
        href="/perks"
        class="block rounded border border-native-blue-400 p-4 text-xl"
        >Perks →</a
      >
    </section>
  </section>
</template>

<script lang="ts">
import Tier from '@components/Join/Tier.vue'
import { tiers as sourceTiers } from '@constants/tier'
import type { Tiers } from '@constants/tier'
import { providers } from 'ethers'
import { composeTiers } from '@fixtures/utility'
import { UndefinedOr } from '@devprotocol/util-ts'
import { defineComponent } from '@vue/runtime-core'
import { CurrencyOption } from '@constants/currencyOption'

const provider = new providers.JsonRpcProvider(
  import.meta.env.PUBLIC_WEB3_PROVIDER_URL
)
const tokenAddress = import.meta.env.PUBLIC_PROPERTY_ADDRESS

type Data = {
  currency: 'dev' | 'eth'
  tiers: {
    [key in CurrencyOption]: UndefinedOr<Tiers>
  }
}

export default defineComponent({
  name: 'JoinClub',
  data(): Data {
    return {
      currency: 'dev',
      tiers: { dev: [...sourceTiers], eth: undefined },
    }
  },
  async mounted() {
    const input = new FormData(this.$refs.form as HTMLFormElement).get(
      'input'
    ) as null | Data['currency']
    this.currency = input as 'dev' | 'eth'
    this.tiers = await composeTiers({
      sourceTiers,
      provider,
      tokenAddress,
    })
  },
  methods: {
    async switchInputs(ev: Event) {
      const { value } = ev.target as HTMLInputElement
      this.currency = value as 'dev' | 'eth'
    },
  },
  components: {
    Tier,
  },
})
</script>
