// src/plugins/admin/CurrencyMembershipInfo.tsx
import React, { useState, useEffect } from 'react'

import { tokenInfo } from '@constants/common'
import { usdByCurrency } from '@fixtures/coingecko/api'
import { ethers, type Contract, type Signer, formatUnits } from 'ethers'
import {
  address,
  defaultAddress,
  swapAndStakeAddressAbi,
} from './utils/swapAndStake'

type Props = {
  chainId: number
  currency: string
  allCurrencyIndex: number
  isYourWithdrawable: boolean
  uniqueBeneficiaries: string[]
  updateWithdrawableInDollars: (allCurrencyIndex: number, value: string) => void
}

const CurrencyMembershipInfo = (props: Props) => {
  const [signer, setSigner] = useState<Signer>()
  const [isClaiming, setIsClaiming] = useState<boolean>()
  const [withdrawable, setWithdrawable] = useState<string>()
  const [connection, setConnection] = useState<any>(undefined)
  const [isFetchingData, setIsFetchingData] = useState<boolean>()
  const [withdrawableInDollars, setWithdrawableInDollars] = useState<string>()
  const [swapAndStakeContract, setSwapAndStakeContract] = useState<Contract>()

  useEffect(() => {
    const checkConnection = async () => {
      const _connection = await import('@devprotocol/clubs-core/connection')
      setConnection(_connection)
    }

    checkConnection()
  }, [props])

  useEffect(() => {
    if (!connection) {
      return
    }

    setSigner(connection.connection().signer.getValue())
    connection.connection().signer.subscribe((s: Signer) => setSigner(s))
  }, [connection])

  useEffect(() => {
    const swapAndStakeAddress =
      address.find((a) => a.chainId === props.chainId)?.address ||
      defaultAddress.address

    setSwapAndStakeContract(
      new ethers.Contract(swapAndStakeAddress, swapAndStakeAddressAbi, signer),
    )
  }, [signer])

  useEffect(() => {
    fetchWithdrawable()
  }, [swapAndStakeContract])

  const fetchWithdrawable = async () => {
    if (!props.chainId || !swapAndStakeContract || !signer) {
      return
    }

    setIsFetchingData(true)
    const tokenAddress = tokenInfo[props.currency][props.chainId].address
    const coinGeckoCurrencyId =
      tokenInfo[props.currency][props.chainId].coingeckoCurrencyId

    let withdrawableAmt: string = '0'
    let withdrawableAmtInDollars: string = '0'
    if (props.isYourWithdrawable) {
      const currentAddress = await signer.getAddress()
      const fee: bigint = BigInt(
        await swapAndStakeContract.gatewayFees(currentAddress, tokenAddress),
      )

      withdrawableAmt = formatUnits(
        fee,
        tokenInfo[props.currency][props.chainId].decimals,
      )
      withdrawableAmtInDollars = (
        await usdByCurrency(Number(withdrawableAmt), coinGeckoCurrencyId)
      ).toString()
    } else {
      let totalWithdrawable: bigint = BigInt('0')
      for (const beneficiary of props.uniqueBeneficiaries) {
        const fee: bigint = BigInt(
          await swapAndStakeContract.gatewayFees(beneficiary, tokenAddress),
        )
        totalWithdrawable = totalWithdrawable + fee
      }

      withdrawableAmt = formatUnits(
        totalWithdrawable,
        tokenInfo[props.currency][props.chainId].decimals,
      )
      withdrawableAmtInDollars = (
        await usdByCurrency(Number(withdrawableAmt), coinGeckoCurrencyId)
      ).toString()
    }

    setWithdrawable(withdrawableAmt)
    setWithdrawableInDollars(withdrawableAmtInDollars)
    props.updateWithdrawableInDollars(
      props.allCurrencyIndex,
      withdrawableAmtInDollars,
    )
    setIsFetchingData(false)
  }

  const claimWithdrawable = async (tokenSymbol: string) => {
    if (
      !props.chainId ||
      !signer ||
      !swapAndStakeContract ||
      !props.isYourWithdrawable
    ) {
      return
    }

    setIsClaiming(true)
    const tokenAddress = tokenInfo[tokenSymbol][props.chainId].address
    const txReceipt = await swapAndStakeContract.claim(tokenAddress)
    await txReceipt.wait(1) // TODO: detect success failure
    setIsClaiming(false)
  }

  return (
    <section className="mt-[18px] flex items-center justify-between gap-[18px]">
      <p className="w-[23%] text-base font-bold">
        {new Intl.NumberFormat(undefined, {
          minimumFractionDigits: 2,
          maximumFractionDigits: 3,
        }).format(Number(withdrawable) || 0)}{' '}
        {props.currency}
      </p>
      <p className="grow text-base font-bold opacity-50">
        ≈ $
        {new Intl.NumberFormat(undefined, {
          minimumFractionDigits: 2,
          maximumFractionDigits: 3,
        }).format(Number(withdrawableInDollars) || 0)}
      </p>
      <button
        onClick={() => claimWithdrawable(props.currency)}
        disabled={!Number(withdrawable)}
        className={`hs-button is-filled w-[27%] px-[22px] py-3.5 ${
          props.isYourWithdrawable ? '' : 'invisible'
        }`}
      >
        Withdraw {props.currency}
      </button>
    </section>
  )
}

export default CurrencyMembershipInfo

// src/plugins/admin/CurrencyMembershipInfo.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { type Signer, ethers, formatUnits, Contract, getBigInt } from 'ethers'

  import { tokenInfo } from '@constants/common'
  import { address, defaultAddress, swapAndStakeAddressAbi } from './utils/swapAndStake'

  export let chainId: number
  export let currency: string
  export let signer: Signer | undefined
  export let allBeneficiaries: string[] = []
  export let isYourWithdrawable: boolean = false

  let withdrawable: string = ''
  let isClaming: boolean = false
  let isFetchingData: boolean = false
  let swapAndStakecontract: Contract | undefined = undefined

  onMount(async () => {
    await setContract()
    await fetchWithdrawable()
  })

  const setContract = async () => {
    if (!chainId || !signer) {
      return
    }

    const swapAndStakeAddress =
      address.find((a) => a.chainId === chainId)?.address ||
      defaultAddress.address

    swapAndStakecontract = new ethers.Contract(
      swapAndStakeAddress,
      swapAndStakeAddressAbi,
      signer,
    )
  }

  const fetchWithdrawable = async () => {
    if (!chainId || !swapAndStakecontract || !signer) {
      return
    }

    isFetchingData = true
    const tokenAddress = tokenInfo[currency][chainId].address

    if (isYourWithdrawable) {
      const currentAddress = await signer.getAddress()
      const fee: bigint = BigInt(await swapAndStakecontract.gatewayFees(currentAddress, tokenAddress))
      withdrawable = formatUnits(fee, tokenInfo[currency][chainId].decimals)
    } else {
      let totalWithdrawable: bigint = BigInt('0')
      for (const beneficiary of allBeneficiaries) {
        const fee: bigint = BigInt(await swapAndStakecontract.gatewayFees(beneficiary, tokenAddress))
        totalWithdrawable = totalWithdrawable + fee
      }
      withdrawable = formatUnits(totalWithdrawable, tokenInfo[currency][chainId].decimals)
    }

    isFetchingData = false
  }

  const claimWithdrawable = async (tokenSymbol: string) => {
    if (!chainId || !signer || !swapAndStakecontract || !isYourWithdrawable) {
      return
    }

    isClaming = true
    const tokenAddress = tokenInfo[tokenSymbol][chainId].address
    const txReceipt = await swapAndStakecontract.claim(tokenAddress)
    await txReceipt.wait(1) // TODO: detect success failure
    isClaming = false
  }
</script>

<section class="mt-[18px] flex items-center gap-[18px] justify-between">
  <p class="w-[23%] font-bold text-base">{
    new Intl.NumberFormat(undefined,{ minimumFractionDigits: 2, maximumFractionDigits: 3 })
      .format(Number(withdrawable) || 0)
  } { currency }</p>
  <p class="grow font-bold text-base opacity-50">≈ $32.000</p>
  <button
    on:click|preventDefault={() => claimWithdrawable(currency)}
    disabled={!Number(withdrawable)}
    class={`hs-button is-filled w-[27%] py-3.5 px-[22px] ${isYourWithdrawable ? '' : 'invisible'}`}
  >
    Withdraw {currency}
  </button>
</section>
